ALTER TYPE "ChatStatus" ADD VALUE IF NOT EXISTS 'ASSIGNED';

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "department" TEXT NOT NULL DEFAULT 'General Support';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "categories" TEXT[] NOT NULL DEFAULT ARRAY['General']::TEXT[];
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "agentStatus" TEXT NOT NULL DEFAULT 'ONLINE';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "maxActiveChats" INTEGER NOT NULL DEFAULT 3;

ALTER TABLE "ChatSession" ADD COLUMN IF NOT EXISTS "assignedAt" TIMESTAMP(3);
ALTER TABLE "ChatSession" ADD COLUMN IF NOT EXISTS "acceptedAt" TIMESTAMP(3);
ALTER TABLE "ChatSession" ADD COLUMN IF NOT EXISTS "transferReason" TEXT;
ALTER TABLE "ChatSession" ADD COLUMN IF NOT EXISTS "queuePosition" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "ChatSession" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'General';
