ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "assignedAt" TIMESTAMP(3);
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "assignedById" TEXT;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "assignmentMode" TEXT NOT NULL DEFAULT 'UNASSIGNED';
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "complaintActionTaken" TEXT;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "complaintResolvedAt" TIMESTAMP(3);
