ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "feedbackRating" INTEGER;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "feedbackText" TEXT;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "feedbackAt" TIMESTAMP(3);
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "complaintSubject" TEXT;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "complaintText" TEXT;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "complaintStatus" TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "complaintAdminReply" TEXT;
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "complaintAt" TIMESTAMP(3);
ALTER TABLE "Ticket" ADD COLUMN IF NOT EXISTS "complaintRepliedAt" TIMESTAMP(3);
